name: Ejercicio 1

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir nombre
        run: echo "Hola, mi nombre es Mario Moncada"
      - name: Imprimir fecha y hora
        run: date
      - name: Imprimir sistema operativo
        run: echo $RUNNER_OS